[package]
name = "loto_sortRS"
version = "0.1.0"
edition = "2021"
authors = ["Guilherme Santos"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
